image: folha/build:base-php-7.3

before_script:
# Install node
- curl -sL https://rpm.nodesource.com/setup_12.x | bash - 
- yum install -y nodejs

Lint && Build:
  stage: test
  script:
    - npm install --progress=false
    - npm run lint
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist